import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "@radix-ui/themes/styles.css"
import { Theme, ThemePanel } from "@radix-ui/themes"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme appearance="dark" accentColor="blue" grayColor="sand" panelBackground="solid" radius="full" scaling="90%">
          {children}
        </Theme>
      </body>
    </html>
  )
}
